name: VERA RFC
description: Wijzigingsverzoek voor VERA
title: "[RFC]: "
labels: ["Vastgoed", "Verhuur","Referentiedata"]
body:
  - type: markdown
    attributes:
      value: |
        Vul onderstaande velden zo volledig mogelijk in.
  - type: input
    id: app-version
    attributes:
      label: VERA versie
      placeholder: bijv. v2.1.0
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: Te verwachten impact
      options:
        - Laag
        - Gemiddeld
        - Hoog
        - Kritiek
  - type: textarea
    id: steps
    attributes:
      label: Onderbouwing
      placeholder: Hoe kunnen we deze bug terugvinden?
    validations:
      required: true
