
name: VERA RFC
description: Wijzigingsverzoek voor VERA
title: "[RFC]: "
labels: ["Vastgoed", "Verhuur", "Referentiedata"]

body:
  - type: markdown
    attributes:
      value: |
        Vul onderstaande velden zo volledig mogelijk in.

  - type: textarea
    id: probleem-omschrijving
    attributes:
      label: Probleemomschrijving
      placeholder: Wat gaat er nu mis of wat ontbreekt nu in de standaard?
    validations:
      required: true

  - type: textarea
    id: voorgestelde-wijziging
    attributes:
      label: Voorgestelde wijziging
      placeholder: Hoe zou de wijziging eruit moeten zien?
    validations:
      required: true

  - type: dropdown
    id: soort
    attributes:
      label: Soort RFC
      options:
        - Foutcorrectie
        - Uitbreiding of nieuwe functionaliteit
        - Wijziging bestaande functionaliteit
    validations:
      required: true

  - type: input
    id: versie
    attributes:
      label: VERA versie
      placeholder: bijv. v4.3.
      
name: VERA RFC
description: Wijzigingsverzoek voor VERA
title: "[RFC]: "
labels: ["Vastgoed", "Verhuur", "Referentiedata"]

body:
  - type: markdown
    attributes:
      value: |
        Vul onderstaande velden zo volledig mogelijk in.

  - type: textarea
    id: probleem-omschrijving
    attributes:
      label: Probleemomschrijving
      placeholder: Wat gaat er nu mis of wat ontbreekt nu in de standaard?
    validations:
      required: true

  - type: textarea
    id: voorgestelde-wijziging
    attributes:
      label: Voorgestelde wijziging
      placeholder: Hoe zou de wijziging eruit moeten zien?
    validations:
      required: true

  - type: dropdown
    id: soort
    attributes:
      label: Soort RFC
      options:
        - Foutcorrectie
        - Uitbreiding of nieuwe functionaliteit
        - Wijziging bestaande functionaliteit
    validations:
      required: true

  - type: input
    id: versie
    attributes:
      label: VERA versie
      placeholder: bijv. v4.3.
